### ISSUE TITLE
Mismatching scores

### ISSUE THREAD

**Issue by zhangtaowhu** [Illumina/SpliceAI#10]
I run the script as spliceai -I input.vcf -O output.vcf -R hg37.genome.fa for my vcf files. And I also extract the score from Illumina predicting data files [Predicting_splicing_from_primary_sequence-66029966]. 
Most of variants have matched scores from both. But a few of them are mismatching. 
For examples:
16:57998386:C:G
SpliceAI Illumina predicting data file:
SYMBOL=CNGB1;STRAND=-;TYPE=I;DIST=5;DS_AG=0.0000;DS_AL=**0.0004**;DS_DG=0.0000;DS_DL=0.9000;DP_AG=-28;DP_AL=5;DP_DG=-19;DP_DL=5
SpliceAI running:
SpliceAI=G|CNGB1|0.00| **0.81**|0.01|0.90|-64|62|-125|5

1:216495345:T:C  
SpliceAI Illumina predicting data file: SYMBOL=USH2A;STRAND=-;TYPE=I;DIST=-27;DS_AG=0.0235;DS_AL=0.0000;DS_DG=0.0000;DS_DL=0.0000;DP_AG=17;DP_AL=-2;DP_DG=-27;DP_DL=-2
SpliceAI=C|USH2A|0.02|0.27|0.00|0.17|17|-2|-27|-120

Noted: Why some DP alters are different?
Please help me figure out the reason.
Many thanks!

**Comment by kishorejaganathan** [comment]
There are two differences between the current software's output and the one we used to generate the scores provided with the paper:
- In the paper, for each variant, we looked for splicing changes up to 50 positions on either side of the variant. In the current version, we look for 500 positions on either side. In the CNGB1 example, notice that the 0.81 value was predicted to be 62 positions away from the variant (this was not caught earlier because we stopped looking at 50 positions).
- In the data we provided, we also filter out scores which correspond to increase in the strength of a canonical site and decrease in the strength of a non-canonical site, as these are not likely to cause rare genetic diseases.

We will document this in the README section soon.

**Comment by zhangtaowhu** [comment]
kishorejaganathan, Thanks a lot for your kind help!!!

**Comment by zhangtaowhu** [comment]
> There are two differences between the current software's output and the one we used to generate the scores provided with the paper:
> 
> * In the paper, for each variant, we looked for splicing changes up to 50 positions on either side of the variant. In the current version, we look for 500 positions on either side. In the CNGB1 example, notice that the 0.81 value was predicted to be 62 positions away from the variant (this was not caught earlier because we stopped looking at 50 positions).
> * In the data we provided, we also filter out scores which correspond to increase in the strength of a canonical site and decrease in the strength of a non-canonical site, as these are not likely to cause rare genetic diseases.
> 
> We will document this in the README section soon.


Does it mean we might miss some information when dealing with the deep intronic variants deeper than 500bp. [ In the current version, we look for 500 positions on either side.]

**Comment by kishorejaganathan** [comment]
No, it does not. What I mean by that statement is the following: A variant can alter splicing either at the position of the variant, or in nearby positions right? For example, if the variant affects the branch point, the position of splicing change will be 20-50 nucleotides downstream. What we did earlier was to look for changes +/-50 positions away from the variant to alleviate computational issues. The software looks for +/-500 positions. 

Even if the variant is deep into the intron, the position of splicing change is not 1000s of positions away. Most of the time, it is <50nt away, so the output of the software and the supplemental data should be consistent with each other. A few examples pop up where the distance is higher, the number of examples that require >500nt away should be extremely low.

**Comment by kishorejaganathan** [comment]
To more precisely answer your question, in case you are considering the scenario where a deep intronic variant affects the closest splice site, yes we will be missing those because the splice site is too far away from the variant. In the file `spliceai/utils.py` (line 89), you can change 
```
def get_delta_scores(record, ann, cov=1001):
```
to
```
def get_delta_scores(record, ann, cov=10001):
```
It will slow down the scoring by a little bit, but that's alright if you don't have too many variants.

**Comment by zhangtaowhu** [comment]
kishorejaganathan, 
Sincere appreciation for your detailed explanation!
