### ISSUE TITLE
delta score VCFs

### ISSUE THREAD

**Issue by rmccoy7541** [Illumina/SpliceAI#12]
Thanks for this important resource. I am currently working with the whole genome delta scores provided on BaseSpace (whole_genome_filtered_spliceai_scores.vcf.gz). I am wondering whether these include predictions of both essential and cryptic splice mutations. 

If both, how did you distinguish these two categories for your paper? Is this defined by distance from the nearest splice site (i.e., the "DIST" INFO field in the VCF)?

**Comment by kishorejaganathan** [comment]
Your understanding is correct. The file whole_genome_filtered_spliceai_scores.vcf.gz contains the delta scores for all possible SNVs in the genic regions (regardless of whether they are cryptic or essential). For the analyses in the paper, subsets of variants were considered based on what we're interested in. A splice variant is categorized as essential if the variant falls within the first or the last two bases of a known intron (these are filtered out for all analyses), and cryptic if otherwise. Indeed, this can be figured out using the DIST and the TYPE fields (DIST has to be -1, -2, 1, or 2 and TYPE has to be I).
