### ISSUE TITLE
How to  interpret Delta position in insertion/deletion variants

### ISSUE THREAD

**Issue by Manuel-DominguezCBG** [Illumina/SpliceAI#124]
How do you work out what the base is from an insertion/deletion eg: NM_001355006.2(NPM1):c.860_863dup – at position -16 Delta score of 0.99 – where is position -16 (beginning or end of duplication?)?

**Comment by Manuel-DominguezCBG** [comment]
I have been playing around with del and dup variants to see how this works. I have seen that in dup is the end of the variant what is considered to compute the DP however in deletions is the beginning as shown below

![Untitled](https://github.com/Illumina/SpliceAI/assets/74112779/c419bb6f-7bd6-49c8-976c-7e41253be5ac)

is this correct? and is this applicable for the four DP given by the tools??

Thanks

MD

**Comment by kishorejaganathan** [comment]
The logic for insertion and deletion is approximate as we cannot map one-to-one between ref and alt sequences. We require the ref length to be 1 for insertions and alt length to be 1 for deletions. The following code
https://github.com/Illumina/SpliceAI/blob/b083eb5f8f0d773c7c977aac0c45880d47ca18b7/spliceai/utils.py#L165-L176
contains all the operations: 
- For insertions, the max of all the inserted positions is used as the alt score for that position. The rest of the calculations are similar to SNVs as the alt now contains only one score.
- For deletions, we insert 0 splice scores for all the deletions to ensure that the ref and alt sequence length is the same. The rest of the calculations are same as SNVs.

This is a heuristic which works most of the time, but there are examples where the scores are high because of incorrect one-to-one map between ref and alt sequences.
