### ISSUE TITLE
Transcript Dependent Scores

### ISSUE THREAD

**Issue by officedronestrike** [Illumina/SpliceAI#127]
I have a question about this variant in particular, but I also need clarification regarding how SAI generates scores associated with differed transcripts. I was under the impression that the model was essentially transcript agnostic. But in this example, SAI predicts different scores depending on the transcript. I cannot seem to find any explanation of why this might be, or any discussion how alternative native transcripts are incorporated into the model. In this example in particular, ENST00000388922.9_3 and ENST00000419526.6_1 have equivalent splicing at this intron, and this I can't see any reason they should be so different in the first place. Any basic information you can share about how/why SAI lookup returns transcript-dependent scores would be very helpful.     

https://spliceailookup.broadinstitute.org/#variant=NM_000020.3(ACVRL1)%3Ac.1378-156_1378-155delinsAG&hg=37&distance=500&mask=1

**Comment by kishorejaganathan** [comment]
SpliceAI uses 10K RNA (not DNA) context nucleotides to make a prediction. The transcript information is only used to determine where RNA begins and ends. If you run out of RNA before getting 5K upstream or downstream context, we pad the remaining length with Ns. Because of this, two different transcripts might get two different scores especially if the variant is close to the edge of one of the transcripts.
