### ISSUE TITLE
ValueError: all the input array dimensions for the concatenation axis must match exactl

### ISSUE THREAD

**Issue by lindsay-liang** [Illumina/SpliceAI#30]
I'm running a WGS VCF through spliceAI and got this traceback:
```
raceback (most recent call last):
  File "/usr/local/bin/spliceai", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/spliceai/__main__.py", line 72, in main
    scores = get_delta_scores(record, ann, args.D, args.M)
  File "/usr/local/lib/python3.6/site-packages/spliceai/utils.py", line 168, in get_delta_scores
    y = np.concatenate([y_ref, y_alt])
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 101 and the array at index 1 has size 122
```

With this command:

```
spliceai -I brain-eQTL-235-19-02-2018.gt.snp.indel.recal.vcf.bgz -O brainVar-splice.vcf -R Homo_sapiens_assembly38.fasta -A grch38
```

And it looks like the variant spliceAI failed on was this:
```
chr1    1028996 .       CAAGGAACCGAGCCCCAGCCCCTCGTGGGCCAAGGGCGCCCACACCCACGCCACCCTCTCCCAAGGAACCGAGCCCCAGCCCCTCGTGGGCCAAGGGCGCCCACAGCCACGCCACCCTTTCCG     C,*
```

I know that previously spliceAI had trouble with variants of length > 500 but this one is 124nt.
Any help on this is greatly appreciated!

**Comment by kishorejaganathan** [comment]
Dear Lindsay,
We changed the default parameters during the update from v1.2.1 to v1.3 in order to be consistent with the precomputed files that we have provided. Moving forward, with the default parameters, deletions greater than 100nt will cause this issue (I will put in a patch to automatically take care of this gracefully during the next update). You have two options:

1. Prefilter the files to remove all deletions greater than 100nt.
2. Set the -D parameter to 500 or something large (the default was 500 before, it is 50 now). 2xD is the maximum deletion that can be tolerated by SpliceAI currently. 

Let me know if this doesn't help.

Regards,
Kishore
