### ISSUE TITLE
Input data and Tensorflow version2

### ISSUE THREAD

**Issue by SIJAE-WOO** [Illumina/SpliceAI#71]
Hi,

SpliceAI is so amazing. I'm trying to reproduce spliceAI model.
I have two questions about spliceAI.
First, do you have spliceAI modeling codes written with tensorflow2?
Second, spliceAI input data are composed of GENCODE canonical and GTEx.
How did you select GENCODE canonical and GTEx data for input? (ex. totally random selection, one (GENCODE) by one (GTEx))

Thank you very much,

Sijae Woo

**Comment by kishorejaganathan** [comment]
Dear Sijae,
- SpliceAI modeling code can be found here: https://basespace.illumina.com/s/otSPW8hnhaZR They are written in Keras 2.0.5 (with Tensorflow 1.4 backend). I think the changes should be minimal in order to get it to work with the latest versions of Keras (and Tensorflow backend).
- We performed a union of the splice sites from GENCODE canonical and GTEx data in order to obtain the final list of splice sites for training. Once the union operation was made, there was no difference in the way we treated splice sites coming from GENCODE or GTEx.

**Comment by SIJAE-WOO** [comment]
Thank you very much! Your comment solved my trouble things.
Sijae

**Comment by SIJAE-WOO** [comment]
Dear Kishore,

Thank you for your comment, I have been reproducing SpliceAI in the Tensorflow v2. But, I met some problems. 
First, I made and checked a union of the splice sites from GENCODE canonical and GTEx data. All splice sites of GENCODE canonical are included in GTEx data when I checked. Then, I trained the SpliceAI model with a union of GENCODE canonical and GTEx data (practically with only GTEx data). Although I trained the SpliceAI model with your code, the predicted delta scores in my trained models are more or less (sometimes quite) different from your models. Is a union of GENCODE canonical and GTEx data that you mentioned a real sum of GENCODE canonical and GTEx data?

**Comment by kishorejaganathan** [comment]
Dear Sijae,
- The GTEx file contains the union of splice sites found in GENCODE and GTEx, so what you are seeing is the expected behaviour. We don't have a file that has only GTEx junctions.
- Each time you train a deep learning model, there are a few things that change (like initialisations, order in which the data is presented, etc). So you will not get the exact same delta scores, but they should not be too different either. This is one of the reasons why we trained 5 models and took the average.

Regards,
Kishore

**Comment by SIJAE-WOO** [comment]
Thank you for your kind and fast response. I'll retry it!

Kind regards,
Sijae

**Comment by SIJAE-WOO** [comment]
Dear Kishore,

I'm so sorry to ask you repeatedly.
I met some problems with the GTEx RNAseq data processing including OLego. 1) Could you tell me OLego options (or parameter) in addition to (-M 4)? It would be very many SNVs or small indels in GTEx individuals. 2) Did you insert not only SNVs but also small indels into the hg19 reference? 3) I didn't find codes regarding the above in your github, if there are open codes, please let me know.

Regards,
Sijae

**Comment by kishorejaganathan** [comment]
Regarding your questions 1 and 3: The code is packaged here https://pypi.org/project/RNA-APoGee/ with proper documentation.
Regarding your question 2: We inserted only SNVs and ignored INDELs.

**Comment by SIJAE-WOO** [comment]
Thank you every time!!
