### ISSUE TITLE
Distance to event

### ISSUE THREAD

**Issue by angelolimeta** [Illumina/SpliceAI#74]
Hi! 
Really well-made tool and easy to use!

I tried running it on some data and it worked really well. However, i noticed that the distance from mutation to splicing event (Acceptor gain, acceptor loss, etc) seems to be capped at -50bp to 50bp, is there any reason for this?

All the best,
Angelo

**Comment by kishorejaganathan** [comment]
Hi Angelo,
We had empirically observed that most splice variants alter a splice site less than 50bp away (and increasing that number came with a computational cost). In hindsight, we should have used something like 500bp as it allows better identification of exon skipping events (i.e., the variant might be close to the acceptor but the donor score also changes because of skipping). We have added a parameter -D (see readme) which is defaulted to 50, you can set it to 500 or 1000 in order to study long range effects.

Regards,
Kishore
