### ISSUE TITLE
How to leverage a GPU to speed up SpliceAI

### ISSUE THREAD

**Issue by nh13** [Illumina/SpliceAI#78]
I am super curious as a naive user how I can leverage a GPU to speed up this process.  Is there a command line option I need to specify to use the GPU, or do I have to build SpliceAI differently? Is there a specific requirement for the type of GPU, or one you'd recommend?

**Comment by nh13** [comment]
Related to https://github.com/Illumina/SpliceAI/issues/20

**Comment by nh13** [comment]
I am installing via bioconda, so do I need to build manually due to `tensorflow-gpu` isn't installed via bioconda? https://github.com/bioconda/bioconda-recipes/blob/master/recipes/spliceai/meta.yaml

**Comment by kishorejaganathan** [comment]
Once the GPU is properly setup (unrelated to SpliceAI), the only thing you have to do differently to run SpliceAI on GPUs is to install tensorflow-gpu instead of tensorflow. We tried to package them inside SpliceAI but tensorflow did not like that, so we decided that it is best to install it separately.
