### ISSUE TITLE
Sequence-to-Sequence Mode

### ISSUE THREAD

**Issue by nicolasalynn** [Illumina/SpliceAI#79]
Hi, when you discuss in the supplementary portion of your paper the property of the model that allows sequence-to-sequence mode (variable input sequences), I do not understand the mechanism in the actual training of the model. The claim in the paper is that this allows tremendous computational savings, but I do not understand how you are able to obtain probabilities for multiple positions with a single forward pass of the model. Suppose that you have a sequence 15,001 nucleotides long, are you somehow able to run fewer than 5,001 iterations to obtain probabilities for all positions (instead of iteratively computing outputs for each individual position in those central 5,001 nucleotides, and back-propagate error each time)? I referred to the the source you cited, but still could not understand. Any insight is appreciated! Thank you.

**Comment by kishorejaganathan** [comment]
Yes, if we have a sequence 15001 nucleotides long, we get 5001 predictions in the forward pass corresponding to the probabilities for all positions instead of iteratively doing this 5000 times (which will take *much* longer). The key factor here is that predictions for neighboring positions share a lot of computations (esp. early layers) and modeling them in a sequence to sequence manner means that the shared computations will be done only once.

**Comment by nicolasalynn** [comment]
Is there a resource you can point me to that explains how this works programmatically? I was not able to find a source that specifically explains how to write this procedure during training.

**Comment by kishorejaganathan** [comment]
Unfortunately, I could not find a resource that explains these things really well. Your best bet is to go through the training code in detail (provided as part of the supplementary material), hopefully that helps.
