### ISSUE TITLE
Annotation-free predictions?

### ISSUE THREAD

**Issue by Hoeze** [Illumina/SpliceAI#90]
Hi, would it be possible to obtain annotation-free variant effect scores?
I.e. could one pass a variant to SpliceAI and then obtain the different donor/acceptor gain/loss effects for the `+` and `-` strand, _solely based on the DNA sequence_?
Or is the genome annotation absolutely needed?

**Comment by kishorejaganathan** [comment]
You can obtain annotation-free score (solely based on the DNA sequence). However, due to the way the software is implemented, an annotation file is necessary. What you can do is the following: create a dummy annotation file where each gene spans an entire strand of a chromosome. In particular, for humans, you would have an annotation file containing 44 genes (22 chromosomes x 2 strands). Due to an implementation detail, you might also need to specify exon start/end, in which case you can say that the entire gene consists of just one exon spanning the entire chromosome.
