### ISSUE TITLE
Test datasets including variants info

### ISSUE THREAD

**Issue by SIJAE-WOO** [Illumina/SpliceAI#98]
Hi,
I want to reproduce and test SpliceAI with test datasets used in your original article.
But, it seems that there are not test dataset including detailed variants info (ex. coordinate, ref, alt...) used in Figure 2G/4/5/S3/S4/S5.
Could you share the specific variants information for testing?

Thank you very much,
Sijae

**Comment by kishorejaganathan** [comment]
Hi Sijae,
Unfortunately, these steps involve scripts which are tied to our infrastructure because of which they are not runnable by others. The methods section contains all the details of the steps involved, hopefully you should be able to recreate the variant lists (or at least a close approximation) without much difficulty.

Regards,
Kishore
